name: Docker Image CI

on: [push]

defaults:
  build:
    name: Build a docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        run: docker build . --file Dockerfile --tag /Users/thomasnoirclerc/Documents/Efrei-M1/DevOps/tp2
        push: ${{secrets.DOCKER_USER}}/tp2